"""create onboarding_profiles table

Revision ID: 49a73b011b5f
Revises: 69bd711ccd7f
Create Date: 2026-07-29 15:35:06.997278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a73b011b5f'
down_revision: Union[str, Sequence[str], None] = '69bd711ccd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('skill_level', sa.String(), nullable=False),
    sa.Column('goals', sa.String(), nullable=False),
    sa.Column('learning_style', sa.String(), nullable=False),
    sa.Column('feedback_style', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_profiles')
    # ### end Alembic commands ###
